/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.LinkedList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import tad.Cardapio;
import tad.Lista;
import tad.Nodo;
import tad.Pedido;


public class dialogDelivery extends javax.swing.JDialog {

    /**
     * Creates new form dialogDelivery
     */
    Lista lista = new Lista();
    Pedido pedido = new Pedido();
    LinkedList<String> listaPedidosAtendidos = new LinkedList<>();

    public void carregaCardapio() {
        DefaultComboBoxModel dcm = new DefaultComboBoxModel(Cardapio.values());
        ComboCardapio.setModel(dcm);
    }

    public void pedidos() {
        LinkedList<Pedido> listaPedidos = new LinkedList<>();

        for (Nodo nodo = lista.getPrimeiro(); nodo != null; nodo = nodo.getAnterior()) {
            listaPedidos.add(nodo.getPedido());
        }
        DefaultListModel dlm = new DefaultListModel();
        dlm.addAll(listaPedidos);
        ListPedidos.setModel(dlm);
    }

    public void pedidosAtendidos() {
        DefaultListModel dlm = new DefaultListModel();
        dlm.addAll(listaPedidosAtendidos);
        ListaAtendidos.setModel(dlm);
    }

    public void itens() {
        DefaultListModel dlm = new DefaultListModel();
        dlm.addAll(pedido.getItensCardapio());
        ListItens.setModel(dlm);
    }

    public void inicializa() {
        TextTempo.setText("0");
        TextValor.setText("0");
        ComboCardapio.setSelectedIndex(0);
        pedido = new Pedido();
        itens();
        ComboCardapio.requestFocus();
    }

    public dialogDelivery(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboCardapio = new javax.swing.JComboBox();
        TextTempo = new javax.swing.JTextField();
        TextValor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListItens = new javax.swing.JList();
        ButtonAdicionar = new javax.swing.JButton();
        ButtonFinalizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListPedidos = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaAtendidos = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Cardapio");

        jLabel2.setText("Tempo entrega");

        jLabel3.setText("Valor Total");

        TextTempo.setEditable(false);

        TextValor.setEditable(false);

        ListItens.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        ListItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListItensMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListItens);

        ButtonAdicionar.setText("Adicionar");
        ButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdicionarActionPerformed(evt);
            }
        });

        ButtonFinalizar.setText("Finalizar Pedido");
        ButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFinalizarActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(ListPedidos);

        jScrollPane1.setViewportView(ListaAtendidos);

        jLabel4.setText("Pedidos:");

        jLabel5.setText("Pedidos atendidos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextValor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TextTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(ButtonFinalizar)
                        .addGap(48, 48, 48))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ComboCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonAdicionar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ComboCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAdicionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TextTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonFinalizar))
                .addGap(49, 49, 49))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.carregaCardapio();
        this.itens();
        this.inicializa();

        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                for (Nodo nodo = lista.getPrimeiro(); nodo != null; nodo = nodo.getAnterior()) {
                    nodo.getPedido().setTotalTempo(nodo.getPedido().getTotalTempo() - 1);
                    if (nodo.getPedido().getTotalTempo() <= 0) { 
                        listaPedidosAtendidos.add("Pedido" + nodo.getPedido().getPedido() + " atendido."); 
                        lista.removeInicio(); 
                        pedidosAtendidos(); 
                    }
                 
                }
                pedidos();
            }
        }, 0, 1000);


    }//GEN-LAST:event_formWindowOpened

    private void ButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdicionarActionPerformed
        Cardapio item = (Cardapio) ComboCardapio.getSelectedItem();
        pedido.getItensCardapio().add(item);
        TextValor.setText(Double.parseDouble(TextValor.getText()) + item.getPreco() + "");
        TextTempo.setText(Integer.parseInt(TextTempo.getText()) + item.getTempoMinutos() + "");
        this.itens();
    }//GEN-LAST:event_ButtonAdicionarActionPerformed

    private void ListItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListItensMouseClicked
        if (evt.getClickCount() == 2) {
            Cardapio item = (Cardapio) ListItens.getSelectedValue();
            if (JOptionPane.showConfirmDialog(null, "Retirar " + item + " do cardapio?") != 0) {
                return;
            }

            pedido.getItensCardapio().remove(item);
            TextValor.setText(Double.parseDouble(TextValor.getText()) - item.getPreco() + "");
            TextTempo.setText(Integer.parseInt(TextTempo.getText()) - item.getTempoMinutos() + "");
            this.itens();
        }
    }//GEN-LAST:event_ListItensMouseClicked

    private void ButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFinalizarActionPerformed
        if (pedido.getItensCardapio().size() == 0) {
            JOptionPane.showMessageDialog(null, "Pedido sem itens!");
            return;
        }

        pedido.setDataHoraPedido(LocalDateTime.now());
        pedido.setTotalTempo(Integer.parseInt(TextTempo.getText()));
        pedido.setTotalPreco(Double.parseDouble(TextValor.getText()));

        lista.insereOrdenado(pedido);
        this.inicializa();
        this.pedidos();
    }//GEN-LAST:event_ButtonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogDelivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogDelivery dialog = new dialogDelivery(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdicionar;
    private javax.swing.JButton ButtonFinalizar;
    private javax.swing.JComboBox ComboCardapio;
    private javax.swing.JList ListItens;
    private javax.swing.JList ListPedidos;
    private javax.swing.JList<String> ListaAtendidos;
    private javax.swing.JTextField TextTempo;
    private javax.swing.JTextField TextValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
